/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3066.0) */

#include "ble_none_display.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside none Display packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside none Display packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_DISPLAY_CONFIGURATION_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Display Configuration. */ 
#define MAX_METRICS_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Metrics. */ 
#define MAX_BUTTONS_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Buttons. */ 

/**@brief Function for encoding Display Configuration.
 *
 * @param[in]   p_display_configuration              Display Configuration characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t display_configuration_encode(ble_none_display_display_configuration_t * p_display_configuration, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint16_encode(&p_display_configuration->configuration, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Display Configuration.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t display_configuration_decode(uint8_t data_len, uint8_t * p_data, ble_none_display_display_configuration_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->configuration); 

    return pos;
} 
/**@brief Function for encoding Metrics.
 *
 * @param[in]   p_metrics              Metrics characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t metrics_encode(ble_none_display_metrics_t * p_metrics, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_metrics->heart_beat_bpm;
    len += bds_uint16_encode(&p_metrics->speed_kmh, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_metrics->cadence_rpm, &encoded_buffer[len]); 
    len += bds_uint32_encode(&p_metrics->total_height, &encoded_buffer[len]); 
    len += bds_uint32_encode(&p_metrics->distance, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Metrics.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t metrics_decode(uint8_t data_len, uint8_t * p_data, ble_none_display_metrics_t * p_write_val)
{
    uint8_t pos = 0;
    p_write_val->heart_beat_bpm = p_data[pos++]; 
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->speed_kmh); 
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->cadence_rpm); 
    pos += bds_uint32_decode((data_len-pos), &p_data[pos], &p_write_val->total_height); 
    pos += bds_uint32_decode((data_len-pos), &p_data[pos], &p_write_val->distance); 

    return pos;
} 
/**@brief Function for encoding Buttons.
 *
 * @param[in]   p_buttons              Buttons characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t buttons_encode(ble_none_display_buttons_t * p_buttons, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_buttons->button;
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_none_display       none Display Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_none_display_t * p_none_display, ble_evt_t * p_ble_evt)
{
    p_none_display->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_none_display       none Display Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_none_display_t * p_none_display, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_none_display->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_none_display       none Display Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_none_display_t * p_none_display, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_none_display->display_configuration_handles.value_handle)
    {
        if(p_none_display->evt_handler != NULL)
        {
            ble_none_display_evt_t evt;
            evt.evt_type = BLE_NONE_DISPLAY_DISPLAY_CONFIGURATION_EVT_WRITE;
            display_configuration_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.display_configuration);
            p_none_display->evt_handler(p_none_display, &evt);
        }
    }
    if(p_ble_evt->handle == p_none_display->metrics_handles.value_handle)
    {
        if(p_none_display->evt_handler != NULL)
        {
            ble_none_display_evt_t evt;
            evt.evt_type = BLE_NONE_DISPLAY_METRICS_EVT_WRITE;
            metrics_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.metrics);
            p_none_display->evt_handler(p_none_display, &evt);
        }
    }
    if(p_ble_evt->handle == p_none_display->buttons_handles.cccd_handle)
    {
        if(p_none_display->evt_handler != NULL)
        {
            ble_none_display_evt_t evt;
            evt.evt_type = BLE_NONE_DISPLAY_BUTTONS_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_none_display->evt_handler(p_none_display, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_none_display_t * p_none_display, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_none_display->display_configuration_handles.value_handle)
            {
                on_write(p_none_display, &p_auth_req->request.write);
            }
            if (p_auth_req->request.write.handle == p_none_display->metrics_handles.value_handle)
            {
                on_write(p_none_display, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_none_display       none Display Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_none_display_on_ble_evt(ble_none_display_t * p_none_display, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_none_display, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_none_display, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_none_display, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_none_display, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the none Display. */
uint32_t ble_none_display_init(ble_none_display_t * p_none_display, const ble_none_display_init_t * p_none_display_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_none_display->evt_handler = p_none_display_init->evt_handler;
    p_none_display->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0xF0, 0xA9, 0x5C, 0xC7, 0x2A, 0x8D, 0x30, 0x91, 0xC4, 0x43, 0xF5, 0x0C, 0x00, 0x00, 0xC7, 0x89}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x3EFC;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_none_display->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Display Configuration characteristic
    ble_none_display_display_configuration_t display_configuration_initial_value = p_none_display_init->ble_none_display_display_configuration_initial_value; 

    uint8_t display_configuration_encoded_value[MAX_DISPLAY_CONFIGURATION_LEN];
    ble_add_char_params_t add_display_configuration_params;
    memset(&add_display_configuration_params, 0, sizeof(add_display_configuration_params));
    
    add_display_configuration_params.uuid                = 0x91CC;
    add_display_configuration_params.uuid_type           = ble_uuid.type; 
    add_display_configuration_params.max_len             = MAX_DISPLAY_CONFIGURATION_LEN;
    add_display_configuration_params.init_len            = display_configuration_encode(&display_configuration_initial_value, display_configuration_encoded_value);
    add_display_configuration_params.p_init_value        = display_configuration_encoded_value; 
    add_display_configuration_params.char_props.read     = 1; 
    add_display_configuration_params.read_access         = SEC_OPEN; 
    add_display_configuration_params.char_props.write    = 1; 
    add_display_configuration_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_display_configuration_params.is_var_len          = 1; 

    err_code = characteristic_add(p_none_display->service_handle, &add_display_configuration_params, &(p_none_display->display_configuration_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Metrics characteristic
    ble_none_display_metrics_t metrics_initial_value = p_none_display_init->ble_none_display_metrics_initial_value; 

    uint8_t metrics_encoded_value[MAX_METRICS_LEN];
    ble_add_char_params_t add_metrics_params;
    memset(&add_metrics_params, 0, sizeof(add_metrics_params));
    
    add_metrics_params.uuid                = 0xE98C;
    add_metrics_params.uuid_type           = ble_uuid.type; 
    add_metrics_params.max_len             = MAX_METRICS_LEN;
    add_metrics_params.init_len            = metrics_encode(&metrics_initial_value, metrics_encoded_value);
    add_metrics_params.p_init_value        = metrics_encoded_value; 
    add_metrics_params.char_props.read     = 1; 
    add_metrics_params.read_access         = SEC_OPEN; 
    add_metrics_params.char_props.write    = 1; 
    add_metrics_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_metrics_params.is_var_len          = 1; 

    err_code = characteristic_add(p_none_display->service_handle, &add_metrics_params, &(p_none_display->metrics_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Buttons characteristic
    ble_none_display_buttons_t buttons_initial_value = p_none_display_init->ble_none_display_buttons_initial_value; 

    uint8_t buttons_encoded_value[MAX_BUTTONS_LEN];
    ble_add_char_params_t add_buttons_params;
    memset(&add_buttons_params, 0, sizeof(add_buttons_params));
    
    add_buttons_params.uuid                = 0x911E;
    add_buttons_params.uuid_type           = ble_uuid.type; 
    add_buttons_params.max_len             = MAX_BUTTONS_LEN;
    add_buttons_params.init_len            = buttons_encode(&buttons_initial_value, buttons_encoded_value);
    add_buttons_params.p_init_value        = buttons_encoded_value; 
    add_buttons_params.char_props.notify   = 1; 
    add_buttons_params.char_props.read     = 1; 
    add_buttons_params.read_access         = SEC_OPEN; 
    add_buttons_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_buttons_params.is_var_len          = 1; 

    err_code = characteristic_add(p_none_display->service_handle, &add_buttons_params, &(p_none_display->buttons_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Display Configuration. */
uint32_t ble_none_display_display_configuration_set(ble_none_display_t * p_none_display, ble_none_display_display_configuration_t * p_display_configuration)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_DISPLAY_CONFIGURATION_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = display_configuration_encode(p_display_configuration, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_none_display->conn_handle, p_none_display->display_configuration_handles.value_handle, &gatts_value);
}

/**@brief Function for setting the Metrics. */
uint32_t ble_none_display_metrics_set(ble_none_display_t * p_none_display, ble_none_display_metrics_t * p_metrics)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_METRICS_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = metrics_encode(p_metrics, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_none_display->conn_handle, p_none_display->metrics_handles.value_handle, &gatts_value);
}

/**@brief Function for setting the Buttons. */
uint32_t ble_none_display_buttons_set(ble_none_display_t * p_none_display, ble_none_display_buttons_t * p_buttons)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_BUTTONS_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = buttons_encode(p_buttons, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_none_display->conn_handle, p_none_display->buttons_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Buttons. */
uint32_t ble_none_display_buttons_send(ble_none_display_t * p_none_display, ble_none_display_buttons_t * p_buttons)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_none_display->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_BUTTONS_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = buttons_encode(p_buttons, encoded_value);
        hvx_params.handle = p_none_display->buttons_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_none_display->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

