/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3066.0) */

#include "service_if.h"
#include <stdint.h>
#include "ble_dis.h" 
#include "ble_bas.h" 
#include "ble_none_display.h" 

static ble_dis_t    m_dis; 
static ble_bas_t    m_bas; 
static ble_none_display_t    m_none_display; 

uint8_t	m_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value_data_arr[1]; 


/**@brief Function for handling the Device Information events.
 *
 * @details This function will be called for all Device Information events which are passed to
 *          the application.
 *
 * @param[in]   p_device_information   Device Information structure.
 * @param[in]   p_evt   Event received from the Device Information.
 */
static void on_dis_evt(ble_dis_t * p_dis, ble_dis_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for handling the Battery Service events.
 *
 * @details This function will be called for all Battery Service events which are passed to
 *          the application.
 *
 * @param[in]   p_battery_service   Battery Service structure.
 * @param[in]   p_evt   Event received from the Battery Service.
 */
static void on_bas_evt(ble_bas_t * p_bas, ble_bas_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_ENABLED:
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_DISABLED:
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_CCCD_WRITE:
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for handling the none Display events.
 *
 * @details This function will be called for all none Display events which are passed to
 *          the application.
 *
 * @param[in]   p_none_display   none Display structure.
 * @param[in]   p_evt   Event received from the none Display.
 */
static void on_none_display_evt(ble_none_display_t * p_none_display, ble_none_display_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_NONE_DISPLAY_DISPLAY_CONFIGURATION_EVT_WRITE:
            break; 
        case BLE_NONE_DISPLAY_METRICS_EVT_WRITE:
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_dis_init_t    dis_init; 
    ble_bas_init_t    bas_init; 
    ble_none_display_init_t    none_display_init; 
    

    // Initialize Device Information.
    memset(&dis_init, 0, sizeof(dis_init));

    dis_init.evt_handler = on_dis_evt; 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_manufacturer_name_string_initial_value.manufacturer_name, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_model_number_string_initial_value.model_number, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_serial_number_string_initial_value.serial_number, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_hardware_revision_string_initial_value.hardware_revision, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_firmware_revision_string_initial_value.firmware_revision, "INITIAL VALUE"); 
    ble_srv_ascii_to_utf8(&dis_init.ble_dis_software_revision_string_initial_value.software_revision, "INITIAL VALUE"); 
    memset(&dis_init.ble_dis_system_id_initial_value.manufacturer_identifier,
           0x00,
           sizeof(dis_init.ble_dis_system_id_initial_value.manufacturer_identifier));
    memset(&dis_init.ble_dis_system_id_initial_value.organizationally_unique_identifier,
           0x00,
           sizeof(dis_init.ble_dis_system_id_initial_value.organizationally_unique_identifier));
    dis_init.ble_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value.data.list_len = 1;
    dis_init.ble_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value.data.p_list = m_dis_ieee_11073_20601_regulatory_certification_data_list_initial_value_data_arr; 
    dis_init.ble_dis_pnp_id_initial_value.vendor_id_source.vendor_id_source = VENDOR_ID_SOURCE_BLUETOOTH_SIG_ASSIGNED_COMPANY_IDENTIFIER_VALUE_FROM_THE_ASSIGNED_NUMBERS_DOCUMENT; 
    memset(&dis_init.ble_dis_pnp_id_initial_value.vendor_id,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.vendor_id));
    memset(&dis_init.ble_dis_pnp_id_initial_value.product_id,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.product_id));
    memset(&dis_init.ble_dis_pnp_id_initial_value.product_version,
           0x00,
           sizeof(dis_init.ble_dis_pnp_id_initial_value.product_version));

    err_code = ble_dis_init(&m_dis, &dis_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize Battery Service.
    memset(&bas_init, 0, sizeof(bas_init));

    bas_init.evt_handler = on_bas_evt; 
    bas_init.is_battery_level_notify_supported = true;
    memset(&bas_init.ble_bas_battery_level_initial_value.level,
           0x00,
           sizeof(bas_init.ble_bas_battery_level_initial_value.level));

    err_code = ble_bas_init(&m_bas, &bas_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize none Display.
    memset(&none_display_init, 0, sizeof(none_display_init));

    none_display_init.evt_handler = on_none_display_evt; 
    memset(&none_display_init.ble_none_display_display_configuration_initial_value.configuration,
           0x00,
           sizeof(none_display_init.ble_none_display_display_configuration_initial_value.configuration));
    memset(&none_display_init.ble_none_display_metrics_initial_value.heart_beat_bpm,
           0x00,
           sizeof(none_display_init.ble_none_display_metrics_initial_value.heart_beat_bpm));
    memset(&none_display_init.ble_none_display_metrics_initial_value.speed_kmh,
           0x00,
           sizeof(none_display_init.ble_none_display_metrics_initial_value.speed_kmh));
    memset(&none_display_init.ble_none_display_metrics_initial_value.cadence_rpm,
           0x00,
           sizeof(none_display_init.ble_none_display_metrics_initial_value.cadence_rpm));
    memset(&none_display_init.ble_none_display_metrics_initial_value.total_height,
           0x00,
           sizeof(none_display_init.ble_none_display_metrics_initial_value.total_height));
    memset(&none_display_init.ble_none_display_metrics_initial_value.distance,
           0x00,
           sizeof(none_display_init.ble_none_display_metrics_initial_value.distance));
    memset(&none_display_init.ble_none_display_buttons_initial_value.button,
           0x00,
           sizeof(none_display_init.ble_none_display_buttons_initial_value.button));

    err_code = ble_none_display_init(&m_none_display, &none_display_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_dis_on_ble_evt(&m_dis, p_ble_evt); 
    ble_bas_on_ble_evt(&m_bas, p_ble_evt); 
    ble_none_display_on_ble_evt(&m_none_display, p_ble_evt); 
}

ble_bas_t* return_ble_bas_t(void) { return &m_bas; }


